<a href="https://colab.research.google.com/github/kalz2q/4clojure-answer/blob/master/linear_komatsukenzoipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# メモ

線形代数千一夜物語

小松健三

を読む。

ごあいさつ

次の 4 次の行列式の値を求めよ。

$
\left|
\begin{array}{cccc}
1 & 2 & 3 & 4\\
2 & 3 & 4 & 1\\
3 & 4 & 1 & 2\\
4 & 1 & 2 & 3
\end{array}
\right|
$


行和が等しいケースなので、第 1 列に他の列を加えて共通因子の 10 をくくり出し、あとは吐き出しと展開によって、答えは 160

とある。

In [4]:
import numpy as np
A = np.matrix([[1,2,3,4],
[2,3,4,1],
[3,4,1,2],
[4,1,2,3]])
print(A)
print(np.linalg.det(A))

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]
 [4 1 2 3]]
160.00000000000009


数字だけは出たがよくわからない。

sympy でもやってみる。

In [8]:
from sympy.abc import *
from sympy import *
A = Matrix([[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]])
display(A)
display(det(A))

Matrix([
[1, 2, 3, 4],
[2, 3, 4, 1],
[3, 4, 1, 2],
[4, 1, 2, 3]])

160

In [10]:
# 2 x 2 の行列の場合
from sympy import *
a, b, c, d = symbols('a b c d')
A = Matrix([[a, b],[c, d]])
display(A)
det(A)

Matrix([
[a, b],
[c, d]])

a*d - b*c